<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1</name>
   <tag></tag>
   <elementGuidId>7f7146e7-dc07-4064-b4fe-55dd3d9b57c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='16-03-2023อบรบในมหาลัย'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#16-03-2023อบรบในมหาลัย > div.btn-control > #16-03-2023อบรบในมหาลัย</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46934745-10e0-4b46-a097-8512991de742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete</value>
      <webElementGuid>5a6c7823-1279-44cf-b834-ebb9d8081bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>16-03-2023อบรบในมหาลัย</value>
      <webElementGuid>4db3f328-e1cd-4f08-9696-6fe91834ac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลบ</value>
      <webElementGuid>b4a00032-d592-4182-9b83-bdf15590b88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;card&quot;]/div[@id=&quot;item-control&quot;]/app-todo[1]/div[@id=&quot;16-03-2023อบรบในมหาลัย&quot;]/div[@class=&quot;btn-control&quot;]/div[@id=&quot;16-03-2023อบรบในมหาลัย&quot;]</value>
      <webElementGuid>d4b24b36-8b00-4f15-b3b1-c3c45caeac1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='16-03-2023อบรบในมหาลัย'])[2]</value>
      <webElementGuid>384571fe-410b-44e8-9301-8d8416519efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='16-03-2023อบรบในมหาลัย']/div/div[2]</value>
      <webElementGuid>bd678b36-248f-4310-8ace-db8ab279743b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[1]/following::div[1]</value>
      <webElementGuid>afa9e61f-6d24-4ba6-add8-31b2476fb483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::div[5]</value>
      <webElementGuid>488c0fea-2eca-4ee4-87fd-07d8996c4cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[2]/preceding::div[1]</value>
      <webElementGuid>7c16ad73-cec1-4d44-b069-d52e5c9d6f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ลบ'])[2]/preceding::div[2]</value>
      <webElementGuid>aef979e2-c7f3-4bd1-8e44-c1123e7cf439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลบ']/parent::*</value>
      <webElementGuid>95a987fb-cd57-4333-9f93-5f3d82eb8ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>faa179fa-acda-45de-8e4b-2708802fa67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '16-03-2023อบรบในมหาลัย' and (text() = 'ลบ' or . = 'ลบ')]</value>
      <webElementGuid>b0578ac9-1832-4bac-93be-848c481ccbe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
