<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2</name>
   <tag></tag>
   <elementGuidId>c14b8578-e9c6-4025-a608-b936014fc4d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='21-03-2023อ่านหนังสือ'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#21-03-2023อ่านหนังสือ > div.btn-control > #21-03-2023อ่านหนังสือ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2b287dc-b3c0-40ef-a684-56c4e48d860b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete</value>
      <webElementGuid>06c5aa72-c6e0-44c2-be66-68115a0f7e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>21-03-2023อ่านหนังสือ</value>
      <webElementGuid>489d2755-0319-45e4-b052-b01b620f2999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลบ</value>
      <webElementGuid>b2508252-ba1f-41b5-84eb-3a24653b8fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-control&quot;)/app-todo[1]/div[@id=&quot;21-03-2023อ่านหนังสือ&quot;]/div[@class=&quot;btn-control&quot;]/div[@id=&quot;21-03-2023อ่านหนังสือ&quot;]</value>
      <webElementGuid>d90fca66-35f8-46dd-9abc-6f879b441641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='21-03-2023อ่านหนังสือ'])[2]</value>
      <webElementGuid>9ead6d26-cdc8-4663-b463-1b8adf77f360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='21-03-2023อ่านหนังสือ']/div/div[2]</value>
      <webElementGuid>6a27f44a-639e-4d9c-9132-1086b4b76697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[1]/following::div[1]</value>
      <webElementGuid>64735303-afb4-4d71-9fb4-0a4eb2ff2b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::div[5]</value>
      <webElementGuid>494ab79b-6849-4fe5-a17b-7d2c9fe579d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลบ']/parent::*</value>
      <webElementGuid>cdb357fe-081b-45f9-ba72-411578b2f1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>4ff8ddb6-ba50-4adb-b586-48624519325c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '21-03-2023อ่านหนังสือ' and (text() = 'ลบ' or . = 'ลบ')]</value>
      <webElementGuid>eaa0a09c-75a8-4ac7-8b4b-6a0b3490b8b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
