<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>8ca69dba-5ccc-4ab9-aaff-4a6002dadf03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='12-02-2023ออกกำลังกาย'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#12-02-2023ออกกำลังกาย > div.btn-control > #12-02-2023ออกกำลังกาย</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac4de3ef-cb55-42a3-ac42-330787cf704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete</value>
      <webElementGuid>f0c4a955-44ca-4624-9a8c-d44cf08cf850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลบ</value>
      <webElementGuid>9a242d4d-2111-43a8-8dcf-b47bd1497cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;card&quot;]/div[@id=&quot;item-control&quot;]/app-todo[1]/div[@id=&quot;12-02-2023ออกกำลังกาย&quot;]/div[@class=&quot;btn-control&quot;]/div[@id=&quot;12-02-2023ออกกำลังกาย&quot;]</value>
      <webElementGuid>d23ba51f-8e59-4ce3-b685-00e02cc96eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12-02-2023ออกกำลังกาย</value>
      <webElementGuid>4d88298f-4e03-423a-8218-e30402f95aed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='12-02-2023ออกกำลังกาย'])[2]</value>
      <webElementGuid>effc10f1-d166-43cc-a466-e5c51dc668c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='12-02-2023ออกกำลังกาย']/div/div[2]</value>
      <webElementGuid>10fc2fde-13aa-4610-9c74-acffd94d2483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[1]/following::div[1]</value>
      <webElementGuid>3dc31e80-7e67-4ce8-ae03-5031e2632498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::div[5]</value>
      <webElementGuid>176969c9-a3d5-4d04-9b9a-78ceb1089c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[2]/preceding::div[1]</value>
      <webElementGuid>066fa287-0307-4e78-baf8-0b4c580ecc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ลบ'])[2]/preceding::div[2]</value>
      <webElementGuid>e7a83c2d-6569-4ce2-85a6-c7e30e7473e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลบ']/parent::*</value>
      <webElementGuid>0037e487-dd0a-4501-ae5c-5cb3f0e01035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>c070bb98-9d01-4ab0-9191-75ead7c6191c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '12-02-2023ออกกำลังกาย' and (text() = 'ลบ' or . = 'ลบ')]</value>
      <webElementGuid>cafed00a-e1b6-4d48-b468-b788294510a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='12-5-2023aaa']/div/div[2]</value>
      <webElementGuid>165843a6-7d64-4a0d-8443-7699d3d468b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ลบ' or . = 'ลบ')]</value>
      <webElementGuid>4cb4d7a4-3644-411b-b368-a56a15f3ad63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
